### ISSUE TITLE
Scripts not up-to-date

### ISSUE THREAD

**Issue by niowniow** [sonyc-project/dcase2020task5-uststc-baseline#2]
The `setup.sh` download script tries to download the file `audio-dev.tar.gz` which should be `audio.tar.gz`

**Comment by niowniow** [comment]
The baseline.sh is also not up to date. It should be  `source activate sonyc-ust-stc` not `source activate sonyc-ust`

**Comment by jtcramer** [comment]
Good catch! These should now be updated.
